{% set build = 0 %}
{% set mpi = environ['MPI'] or 'mpich' %}
{% set req = {'mpich':'>=3.1', 'openmpi':'>=1.8', 'mpich2':'', 'msmpi':''} %}

package:
  name: mpi4py
  version: 2.0.0

about:
  home: https://bitbucket.org/mpi4py/
  summary: 'Python bindings for MPI'
  license: 'BSD (https://bitbucket.org/mpi4py/mpi4py/src/master/LICENSE.rst)'

source:
# git_url: https://bitbucket.org/mpi4py/mpi4py
# git_rev: master
  path: ../../..

requirements:
  build:
    - python
    - cython >=0.22
    - {{mpi}} {{req[mpi]}} # [not win]
  run:
    - python
    - {{mpi}} {{req[mpi]}} # [not win]

build:
  number: {{build}}
  string: py{{py}}_{{mpi}}_{{build}}
  script: python setup.py install

test:
  imports:
    - mpi4py
    - mpi4py.rc
    - mpi4py.dl # [not win]
    - mpi4py.MPI
