package: mpi4py
user: mpi4py

platform:
 - linux-64
#- linux-32
#- osx-64
#- win-32
#- win-64
engine:
 - python=2.6 cython numpy mpich2
 - python=2.7 cython numpy mpich2
 - python=3.3 cython numpy mpich2
 - python=3.4 cython numpy mpich2
env:
 - CFLAGS=-O0

install:
 - conda config --add channels mpi4py

before_script:
  - python -V
  - cython -V

script:
 - python setup.py install
 - python setup.py clean --all

after_success:
 - mpiexec -n 1 python $PWD/test/runtests.py -v -f --exclude=spawn
 - mpiexec -n 5 python $PWD/test/runtests.py -v -f --exclude=spawn

iotimeout: 120
