package: mpi4py

platform:
 - linux-64
#- linux-32
#- osx-64
#- win-32
#- win-64
engine:
 - python=2 cython numpy mpich2
 - python=3 cython numpy mpich2

script:
 - pip install .
after_success:
 - mpiexec -n 1 python $PWD/test/runtests.py -v -f --no-builddir --exclude=spawn
 - mpiexec -n 5 python $PWD/test/runtests.py -v -f --no-builddir --exclude=spawn
