package: mpi4py
user: mpi4py

platform:
 - linux-64
#- linux-32
#- osx-64
#- win-32
#- win-64
engine:
 - python=2.6
 - python=2.7
 - python=3.3
 - python=3.4
env:
 - MPI=mpich
 - MPI=openmpi
 - MPI=mpich2

install:
 - conda config --add channels mpi4py
 - conda build conf/conda-recipe/

test:
 - conda install --quiet --yes numpy mpi4py
 - mpiexec -n 1 python $PWD/test/runtests.py -v -f -e spawn
 - mpiexec -n 2 python $PWD/test/runtests.py -v -f -e spawn

build_targets:
 files: conda
 channels: main

iotimeout: 120
