package: mpi4py
user: mpi4py

platform:
 - linux-64
#- linux-32
#- osx-64
#- win-32
#- win-64
engine:
 - python=2.6
 - python=2.7
 - python=3.3
 - python=3.4
env:
 - CFLAGS=-O0 MPI=mpich
 - CFLAGS=-O0 MPI=mpich2

install:
 - conda install cython numpy
 - conda config --add channels mpi4py
 - conda install {{environ.get('MPI')}}
 - python setup.py install
 - python setup.py clean --all

test:
 - mpiexec -n 1 python test/runtests.py -v -f --exclude=spawn
 - mpiexec -n 5 python test/runtests.py -v -f --exclude=spawn

iotimeout: 120
