package: mpi4py
user: mpi4py

platform:
 - linux-64
#- linux-32
#- osx-64
#- win-32
#- win-64
engine:
 - python=2.6
 - python=2.7
 - python=3.3
 - python=3.4
 - python=3.5
env:
 - MPI=mpich
 - MPI=openmpi

script:
 - conda config --add channels mpi4py
 - conda build .

build_targets: conda
