{% set build = 1 %}
{% set mpi = environ['MPI'] or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=1.10'} %}

package:
  name: mpi4py
  version: 2.0.0

about:
  home: https://bitbucket.org/mpi4py/
  summary: 'Python bindings for MPI'
  license: 'BSD (https://bitbucket.org/mpi4py/mpi4py/src/master/LICENSE.rst)'

source:
  fn: mpi4py-2.0.0.tar.gz
  url: https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-2.0.0.tar.gz
  md5: 4f7d8126d7367c239fd67615680990e3

requirements:
  build:
    - python
    - {{mpi}} {{req[mpi]}} # [not win]
  run:
    - python
    - {{mpi}} {{req[mpi]}} # [not win]

build:
  number: {{build}}
  string: py{{py}}_{{mpi}}_{{build}}
  script: python setup.py install

test:
  imports:
    - mpi4py
    - mpi4py.rc
    - mpi4py.dl # [not win]
    - mpi4py.MPI
